parameters:
#    showlist_form.example.class: showlist\FormBundle\Example

services:
#    showlist_form.example:
#        class: %showlist_form.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    showlist_form.antispam:
        class: showlist\FormBundle\Antispam\antiSpam
        arguments: [@mailer, %locale%, 3]